
'use client';

import { useEffect, useActionState, useState, type FormEvent } from 'react';
import { useFormStatus } from 'react-dom';
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import * as z from "zod"
import { createHash } from 'crypto';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { addMoneyToWallet } from '@/lib/actions';
import type { User } from '@/lib/definitions';

const AddMoneySchema = z.object({
  amount: z.coerce.number().positive({ message: 'Amount must be greater than zero.' }),
});

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending}>
      {pending ? 'Sending...' : 'Send API Request'}
    </Button>
  );
}

// Note: This is now only for client-side signature generation for debugging
const SECRET_KEY = '904c3acfdc028f495ccc5b60d01dcc49';

export default function AddMoneyDialog({
  isOpen,
  setIsOpen,
  user,
  onBalanceUpdate,
}: {
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
  user: User;
  onBalanceUpdate: (userId: string, newBalance: number) => void;
}) {
  const { toast } = useToast();
  const [state, formAction] = useActionState(addMoneyToWallet, null);
  
  const [formState, setFormState] = useState({
    apiUrl: 'http://gsmd.336699bet.com/makeTransfer.aspx',
    operatorcode: 'i4bi',
    providercode: 'JE',
    username: '',
    password: '',
    referenceid: '',
    type: '0',
    amount: '',
    signature: '',
  });

  useEffect(() => {
    if (isOpen && user) {
      setFormState({
        apiUrl: 'http://gsmd.336699bet.com/makeTransfer.aspx',
        operatorcode: 'i4bi',
        providercode: 'JE',
        username: user.username,
        password: user.password || '',
        referenceid: `MANUAL_${Date.now()}`,
        type: '0', // Deposit
        amount: '100', // Default amount
        signature: '',
      });
    }
  }, [isOpen, user]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormState(prevState => ({
      ...prevState,
      [name]: value,
    }));
  };

  const generateSignature = () => {
    const { amount, operatorcode, password, providercode, referenceid, type, username } = formState;
    if (!amount || !operatorcode || !password || !providercode || !referenceid || !type || !username) {
        toast({ title: "Error", description: "All fields except signature must be filled to generate a signature.", variant: "destructive" });
        return;
    }
    // Signature Formula: MD5(amount + operatorcode + password + providercode + referenceid + type + username + secret_key)
    const stringToSign = `${amount}${operatorcode}${password}${providercode}${referenceid}${type}${username}${SECRET_KEY}`;
    
    // We cannot use Node's 'crypto' here directly in the browser.
    // A pure JS MD5 implementation would be needed for a fully client-side generator.
    // For this debugging purpose, we will log the string to the console.
    // The actual signature will be generated by the server action.
    console.log("String to be signed:", stringToSign);
    toast({ title: "Signature Helper", description: "The string to be signed has been logged to the browser console. The final signature will be generated and used on the server." });
  };
  
  useEffect(() => {
    if (!state || !isOpen) return;

    if (state.success) {
      toast({
        title: 'Success',
        description: state.success,
      });
      if(state.newBalance !== undefined) {
        onBalanceUpdate(user._id, state.newBalance);
      }
      setIsOpen(false);
    }
    if (state.error) {
      toast({
        title: 'Error',
        description: state.error,
        variant: 'destructive',
      });
    }
  }, [state, toast, setIsOpen, onBalanceUpdate, user._id, isOpen]);

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Manual API Request</DialogTitle>
          <DialogDescription>
            Construct and send a manual `makeTransfer` request. All fields are editable.
          </DialogDescription>
        </DialogHeader>
        <form action={formAction} className="max-h-[70vh] overflow-y-auto pr-4">
          <div className="grid gap-4 py-4">
            
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="apiUrl" className="text-right">API URL</Label>
              <Input id="apiUrl" name="apiUrl" value={formState.apiUrl} onChange={handleInputChange} className="col-span-3 font-mono text-xs" />
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="operatorcode" className="text-right">operatorcode</Label>
              <Input id="operatorcode" name="operatorcode" value={formState.operatorcode} onChange={handleInputChange} className="col-span-3" />
            </div>
            
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="providercode" className="text-right">providercode</Label>
              <Input id="providercode" name="providercode" value={formState.providercode} onChange={handleInputChange} className="col-span-3" />
            </div>
            
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="username" className="text-right">username</Label>
              <Input id="username" name="username" value={formState.username} onChange={handleInputChange} className="col-span-3" />
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="password" className="text-right">password</Label>
              <Input id="password" name="password" value={formState.password} onChange={handleInputChange} className="col-span-3" />
            </div>
            
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="referenceid" className="text-right">referenceid</Label>
              <Input id="referenceid" name="referenceid" value={formState.referenceid} onChange={handleInputChange} className="col-span-3" />
            </div>
            
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="type" className="text-right">type</Label>
              <Input id="type" name="type" value={formState.type} onChange={handleInputChange} className="col-span-3" />
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="amount" className="text-right">amount (₹)</Label>
              <Input id="amount" name="amount" type="number" value={formState.amount} onChange={handleInputChange} className="col-span-3" />
            </div>
            
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="signature" className="text-right">signature</Label>
                <div className="col-span-3 flex items-center gap-2">
                    <Input id="signature" name="signature" value={formState.signature} onChange={handleInputChange} className="flex-grow font-mono text-xs" placeholder="Server-generated if empty"/>
                    <Button type="button" variant="outline" size="sm" onClick={generateSignature}>Help</Button>
                </div>
            </div>
            
             {state?.error && (
                <p className="col-span-4 text-center text-sm text-destructive bg-destructive/10 p-2 rounded-md">{state.error}</p>
            )}
            
            {/* Hidden input to pass userId, which is not part of the API call itself but needed for DB update */}
            <input type="hidden" name="userId" value={user._id} />
          </div>
          <DialogFooter>
            <DialogClose asChild>
              <Button type="button" variant="secondary">Cancel</Button>
            </DialogClose>
            <SubmitButton />
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
